Cidr 1374
ciscops/cidrbot pull request #140
Opened 2022-06-15 20:12 UTC by KJStick

2022-06-15 21:11 UTC, jlothian requested changes

2022-06-15 21:11 UTC, jlothian commented on wxt_cidrbot/dynamo_api_handler.py
> +            self.table = self.dynamodb.Table(self.db_room_name)
if you are using different tables for different things, they should each likely have their own variable or entry in a dict, something like that

2022-06-15 21:11 UTC, jlothian commented on wxt_cidrbot/dynamo_api_handler.py
> +            self.table = self.dynamodb.Table(self.db_install_name)
see above

2022-06-15 22:10 UTC, ppajersk approved these changes
Lgtm

2022-06-16 12:57 UTC, jlothian approved these changes
Looks good.

2022-06-16 13:23 UTC, merged