no message for draft pr; made new message for pr converted from draft…
ciscops/cidrbot pull request #150
Opened 2022-07-12 20:49 UTC by KJStick

… to actual pr

2022-07-13 14:04 UTC, jlothian requested changes

2022-07-13 14:04 UTC, jlothian commented on wxt_cidrbot/git_webhook_handler.py
> +
This is probably better written as an if/else - if you need to do some other stuff later on based on the conditions, you won't have to re-do any of the logic flow.

2022-07-13 14:04 UTC, jlothian commented on wxt_cidrbot/git_webhook_handler.py
> +        for reviewer in reviewers:
can't this just be `len(reviewers)`?

2022-07-13 19:05 UTC, jlothian approved these changes
:+1:

2022-07-14 15:23 UTC, ppajersk approved these changes
+1

2022-07-14 15:24 UTC, merged