Added message memory for conversations
ciscops/cidrbot pull request #16
Opened 2021-08-03 17:45 UTC by ppajersk

Added replying to threads to compliment the first change
Added more dialog
Added issue retrieving from a git repo (env var)
Added some placeholder verification when requesting-
-issues from a repo (Will be changed)

2021-08-04 13:14 UTC, jlothian requested changes
General comment - for your module names, either use CamelCase or snake_case, but not both.  I think the python convention is generally snake case.

2021-08-04 13:14 UTC, jlothian commented on wxt_cidrbot/Git_handler.py
> +        self.git_init = Github()
a better name for `git_init` would be something like `git_api_handle` or `git_api` -

2021-08-04 13:14 UTC, jlothian commented on wxt_cidrbot/Git_handler.py
> +        self.repos = self.repos.split(",")
this line should be in __init__

2021-08-04 22:23 UTC, ppajersk commented
Changes should be made. I didn't snake case the class names, they are all 1 word and lowercased. I couldn't find any function names that where CamelCased

2021-08-05 12:42 UTC, jlothian commented
> Necessary changes are be made. I didn't snake case the class names, they are all 1 word and lowercased. I couldn't find any function names that were CamelCased

Looks like you still need to rename the modules - Github_handler, Command_list, etc.

2021-08-05 16:28 UTC, jlothian approved these changes
LGTM

2021-08-05 17:43 UTC, merged